INSERT INTO places (place_name, been_there) VALUES ('Rome', false)
INSERT INTO places (place_name, been_there) VALUES ('Abuja', false)
INSERT INTO places (place_name, been_there) VALUES ('Nouakchott', false)
INSERT INTO places (place_name, been_there) VALUES ('Ouagadougou', false)
INSERT INTO places (place_name, been_there) VALUES ("N'Djamena", true)